channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.9.1
  - decorator=4.4.2
  - matplotlib=3.3.2
  - numpy=1.18.5
  - packaging=20.4
  - pandas=1.1.0
  - pdfminer.six=20200726
  - pip=20.2.1
  - psycopg2=2.8.5
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytorch=1.3.1
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - pip:
      - cx-oracle==8.0.0
